site_name: Promised Worlds Wiki 
site_description: Offical Promised Worlds Wiki 
site_url: https://promisedworlds.github.io/PWiki
repo_url: https://github.com/PromisedWorlds/PWiki
repo_name: PWiki

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home:
    - Overview: index.md
    - Installation: Installation.md
  - Debdeb System:
    - System Overview: Debdeb System.md
    - Debdeb Celestial Bodies:
      - Charr: debdeb/Charr.md
      - Ovin: debdeb/Ovin.md
      - Gurdamma: debdeb/Gurdamma.md
      - Donk: debdeb/Donk.md
      - Kevba's Anomaly: debdeb/Kevba.md
      - Gup: debdeb/Gup.md
      - Lapat: debdeb/Lapat.md
      - Axod: debdeb/Axod.md
      - Umod: debdeb/Umod.md
      - Dorau: debdeb/Dorau.md
      - Bis: debdeb/Bis.md
  - Tuun System:
    - System Overview: Tuun System.md
    - Tuun Celestial Bodies:
      - Hurr: tuun/Hurr.md
      - Rask & Rusk: tuun/Rask-Rusk.md
      - Rem: tuun/Rem.md
      - Flot: tuun/Flot.md
      - Verda: tuun/Verda.md
      - Puf: tuun/Puf.md
      - Glumo: tuun/Glumo.md
      - Noj: tuun/Noj.md
      - Merbel: tuun/Merbel.md
      - Skut: tuun/Skut.md
  - Qeg System:
    - System Overview: Qeg System.md
  - Changelog: Changelog.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
